### ISSUE TITLE
Error: No input network found in stdin.

### ISSUE THREAD

**Issue by USTC-yzy1996** [juliuste/transit-map#5]
I have already run  `npm install -g transit-map` and install the package.
But when I run  `transit-map` , there's an error as follow.
Error: No input network found in stdin.
So, what's the problem with my package? Could you please help me solve this problem?

**Comment by jaller94** [comment]
You have to download a (transit) network as an input. E.g. the [subways of Berlin](https://raw.githubusercontent.com/juliuste/transit-map/master/examples/bvg.input.json) from the examples folder of this repository.
Save the JSON on your computer and pipe it into transit-map:

```bash
npm install -g transit-map
wget https://raw.githubusercontent.com/juliuste/transit-map/master/examples/bvg.input.json
cat bvg.input.json | transit-map
```
For further explanations on how to run transit-map, run:
`transit-map --help`

**Comment by ianfixes** [comment]
```
{
  "nodes":
    [
      {
        "id": "900000096101",
        "label": "S+U Wittenau",
        "metadata": {
          "x": 537.043,
          "y": 674.0319999999999
        }
```

How do `x` and `y` correspond to latitude and longitude?

**Comment by derhuerst** [comment]
As far as I remember, you can use any [projection](https://en.wikipedia.org/wiki/Map_projection) to compute `x`/`y` from longitude/latitude.

`transit-map` assumes they are already projected in a reasonable way, it only "cares" about the visual alignment of the stops, not about the "underlying" geographic location. You can of course use longitude/latitude directly as `x`/`y`, but the transit map will look distorted, depending on place on earth you're using `transit-map` for.

**Comment by ianfixes** [comment]
I figured that, but does this mean that the scale of `x` and `y` is irrelevant?  In other words: are the distances between any pair of stations measured in a particular unit (meters, miles) or is it all automatically scaled away when the map is rendered?

**Comment by juliuste** [comment]
*(Sorry for the late response.)* The scale will be completely ignored, but note that the optimizer restricts the angle for edges in the generated map to those closest to the angle of a line segment in the original map. So while the length will be ignored, the angles (which can correlate with the length of edges) are taken into consideration.

**Comment by juliuste** [comment]
Please re-open if there are any remaining questions.

**Comment by PanaderoCF** [comment]
> You have to download a (transit) network as an input. E.g. the [subways of Berlin](https://raw.githubusercontent.com/juliuste/transit-map/master/examples/bvg.input.json) from the examples folder of this repository.
> Save the JSON on your computer and pipe it into transit-map:
> 
> ```shell
> npm install -g transit-map
> wget https://raw.githubusercontent.com/juliuste/transit-map/master/examples/bvg.input.json
> cat bvg.input.json | transit-map
> ```
> 
> For further explanations on how to run transit-map, run:
> `transit-map --help`

Dear all,

By running the abovementioned code in Windows Powershell, I still get this error (Error: No input network found in stdin in main [reference to appdata\npm\transit-map]) and I don't know why. Even if I save the example bvg.input.json-file in a dedicaded folder in which I run the last command. Could it be related with the installation of Gurobi and AMPL? I downloaded the new packages, but it took me a great effort. Looking forward to the solution.

Kind regards,
Floor

**Comment by derhuerst** [comment]
@PanaderoCF Please provide the whole log of the commands that you have run, including their output.

**Comment by PanaderoCF** [comment]
@derhuerst 
Hereby the command line and output:
`PS C:\Users\flore\Documents> npm install -g transit-map`
`npm WARN deprecated virtual-dom-stringify@3.0.1: use vdom-to-html instead`
`C:\Users\flore\AppData\Roaming\npm\transit-map -> C:\Users\flore\AppData\Roaming\npm\node_modules\transit-map\cli.js`
`+ transit-map@0.1.0`
`added 7 packages from 3 contributors and updated 1 package in 2.536s`

Results in node-module-folder in C:\Users\flore\AppData\Roaming\npm which contains transit-map

`PS C:\Users\flore\Documents> wget https://raw.githubusercontent.com/juliuste/transit-map/master/examples/bvg.input.json -o` `bvg.input.json`

Copies the example.json-file of Berlin Subway into C:\Users\flore\Documents in which I run:
 
`PS C:\Users\flore\Documents> cat graph.json | transit-map > output.svg`
`Error: No input network found in stdin.`
`    at main (C:\Users\flore\AppData\Roaming\npm\node_modules\transit-map\cli.js:56:20)`

Resulting in an empty output.svg-file. I ran this command after:

`Set-ExecutionPolicy -Scope Process -ExecutionPolicy Bypass`

As this would otherwise result in:

`transit-map : File C:\Users\flore\AppData\Roaming\npm\transit-map.ps1 cannot be loaded. The file` `C:\Users\flore\AppData\Roaming\npm\transit-map.ps1 is not digitally signed. You cannot run this script on the current system.` `For more info`
`rmation about running scripts and setting execution policy, see about_Execution_Policies at https:/go.microsoft.com/fwlink/?` 
`LinkID=135170.`
`At line:1 char:18`
`+ cat graph.json | transit-map > output.svg`
`+                  ~~~~~~~~~~~`
`    + CategoryInfo          : SecurityError: (:) [], PSSecurityException`
`    + FullyQualifiedErrorId : UnauthorizedAccess`

**Comment by derhuerst** [comment]
@PanaderoCF Okay, if I'm not missing something, it looks like a bug and/or Windows weirdness. Please open a new Issue with the information from your comment.
